[build]
  publish = "questionnaire"

[build.environment]
  NODE_VERSION = "18"

# Redirect all paths to index.html for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Form handling
[[plugins]]
  package = "@netlify/plugin-form-submissions"